#
# Makefile for FaCT++ kernel reasoning library
#

# -- DO NOT CHANGE THE REST OF FILE --
LIBRARY = Bdd
LTYPE = static

SOURCES = \
          bddio.c\
          bddop.c\
          bvec.c\
          cache.c\
          fdd.c\
          imatrix.c\
          bdd_kernel.c\
          pairs.c\
          prime.c\
          reorder.c\
          tree.c\
          cppext.cpp\

include ../Makefile.include
