#
# Makefile for FaCT++ JNI interface library
#

# -- DO NOT CHANGE THE REST OF FILE --
LIBRARY = FaCTPlusPlusJNI
LTYPE = shared

INCLUDES = -I/System/Library/Frameworks/JavaVM.framework/Headers
USE_IL = ../Kernel ../Bdd

SOURCES = \
	  FaCTPlusPlus.cpp

include ../Makefile.include
